import asyncio
import os
import struct
from datetime import timedelta

import pytest
from sqlalchemy import create_engine, event, func, select
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.db import Base, utcnow
from app.flex import Profile, ProtocolError, RECOMMENDED_FIELDS, crc8, ntcb, read_frame
from app.flex_server import Receiver
from app.flex_store import Store
from app.models import Device, HardwareRecord, LocationPoint, Vehicle

IMEI = '123456789012345'  # Synthetic fixture, never a production device.


def negotiation(fields=RECOMMENDED_FIELDS, version=10):
    bits = {10: 69, 20: 122, 30: 255}[version]
    mask = bytearray((bits+7)//8)
    for n in fields:
        mask[(n-1)//8] |= 0x80 >> ((n-1) % 8)
    return b'*>FLEX\xb0' + bytes([version, version, bits]) + mask


def record(timestamp=None, **overrides):
    stamp = int((timestamp or utcnow()).timestamp())
    fields = {1: 100, 2: 10, 3: stamp, 4: 0, 5: 8, 7: 24, 8: 8*4+3,
              9: stamp, 10: 33000000, 11: 29400000, 13: 30., 14: 90, 19: 12400, 20: 4000}
    fields.update({int(k): v for k, v in overrides.items()})
    return fields


def frame(fields, command=b'A', profile=None):
    profile = profile or Profile(negotiation())
    prefix = b'~'+command+ (b'\x01' if command == b'A' else struct.pack('<I', fields[1]) if command == b'T' else b'')
    body = prefix + profile.layout.pack(*(fields[n] for n in profile.fields))
    return body + bytes([crc8(body)])


@pytest.fixture
def store():
    url = os.environ.get('TEST_DATABASE_URL', 'sqlite://')
    options = {'connect_args': {'check_same_thread': False}, 'poolclass': StaticPool} if url == 'sqlite://' else {}
    engine = create_engine(url, **options)
    if url == 'sqlite://':
        @event.listens_for(engine, 'connect')
        def foreign_keys(connection, _):
            connection.execute('PRAGMA foreign_keys=ON')
    Base.metadata.create_all(engine)
    factory = sessionmaker(engine, expire_on_commit=False)
    with factory() as db:
        db.add(Vehicle(id=1, name='Test'))
        db.flush()
        db.add(Device(id=1, vehicle_id=1, name='Test FLEX', kind='navtelecom', imei=IMEI, token_hash='unusable-fixture'))
        db.commit()
    yield Store(factory)
    Base.metadata.drop_all(engine)
    engine.dispose()


def test_manufacturer_published_vector():
    # Official manual v6, pp118–119. Independent bytes, not generated by our encoder.
    packet = bytes.fromhex('404e544301000000000000001a001b192a3e464c4558b014147af2002000000000000000000000000000')
    profile = Profile(packet[16:])
    assert profile.fields == [1, 2, 3, 4, 7, 19]
    assert profile.ready is False  # Request downgrade to base protocol.
    profile = Profile(negotiation(profile.fields))
    records, ack = profile.records(bytes.fromhex('7e41011e000000b017e11d7456001f142f24'))
    assert records == [{1: 30, 2: 6064, 3: 1450450401, 4: 0, 7: 31, 19: 12052}]
    assert ack[:3] == b'~A\x01'


@pytest.mark.parametrize('command', [b'A', b'T', b'C'])
def test_flex_messages_and_corruption(command):
    p = Profile(negotiation())
    fields = record()
    packet = frame(fields, command)
    assert p.records(packet)[0] == [fields]
    with pytest.raises(ProtocolError):
        p.records(packet[:-1] + bytes([packet[-1] ^ 1]))


def test_profile_rejects_unknown_fields_and_lengths():
    for payload in (negotiation((1, 2, 3, 21)), negotiation()[:-1], b'garbage'):
        with pytest.raises(ProtocolError):
            Profile(payload)
    assert not Profile(negotiation(version=30)).ready


def test_durable_ingestion_replays_and_archive_do_not_replace_live(store):
    current = record()
    store.save(IMEI, [current, current])
    archive = record(utcnow()-timedelta(days=1), **{'1': 99, '19': 11000})
    store.save(IMEI, [archive])
    with store.factory() as db:
        assert db.scalar(select(func.count()).select_from(LocationPoint)) == 2
        assert db.scalar(select(func.count()).select_from(HardwareRecord)) == 2
        d = db.get(Device, 1)
        assert d.health['main_voltage'] == 12.4
        assert d.health['satellites'] == 8
        p = db.scalar(select(LocationPoint))
        assert p.accuracy is None and p.latitude == 55 and p.longitude == 49


@pytest.mark.parametrize('override,reason', [({'8': 1}, 'invalid_navigation'),
    ({'9': int((utcnow()-timedelta(hours=1)).timestamp())}, 'stale_navigation'),
    ({'10': 99*600000}, 'invalid_navigation_values')])
def test_bad_navigation_is_saved_without_fake_fix(store, override, reason):
    store.save(IMEI, [record(**override)])
    with store.factory() as db:
        assert db.scalar(select(func.count()).select_from(LocationPoint)) == 0
        assert db.scalar(select(HardwareRecord)).rejection == reason
        assert db.get(Device, 1).health['navigation_valid'] is False
        assert db.get(Device, 1).last_seen is not None


def test_clock_error_rolls_back_entire_packet(store):
    with pytest.raises(ProtocolError):
        store.save(IMEI, [record(), record(utcnow()+timedelta(hours=1))])
    with store.factory() as db:
        assert db.scalar(select(func.count()).select_from(LocationPoint)) == 0
        assert db.scalar(select(func.count()).select_from(HardwareRecord)) == 0


def test_revoked_and_unknown_devices(store):
    with pytest.raises(ProtocolError):
        store.authorize('999999999999999')
    with store.factory() as db:
        db.get(Device, 1).active = False
        db.commit()
    with pytest.raises(ProtocolError):
        store.save(IMEI, [record()])


def test_tcp_fragmentation_coalescing_ack_and_revocation(store):
    async def run():
        receiver = Receiver(store)
        server = await asyncio.start_server(receiver.handle, '127.0.0.1', 0)
        async with server:
            reader, writer = await asyncio.open_connection('127.0.0.1', server.sockets[0].getsockname()[1])
            handshake = ntcb(b'*>S:'+IMEI.encode(), receiver=1, sender=0)
            for b in handshake:
                writer.write(bytes([b]))
                await writer.drain()
                await asyncio.sleep(0)
            assert (await read_frame(reader, None))[1][2] == b'*<S'
            writer.write(ntcb(negotiation(), receiver=1, sender=0) + frame(record()))
            await writer.drain()
            assert (await read_frame(reader, None))[1][2] == b'*<FLEX\xb0\x0a\x0a'
            ack = await reader.readexactly(4)
            assert ack[:3] == b'~A\x01'
            with store.factory() as db:
                assert db.scalar(select(func.count()).select_from(LocationPoint)) == 1
                db.get(Device, 1).active = False
                db.commit()
            writer.write(frame(record()))
            await writer.drain()
            assert await asyncio.wait_for(reader.read(), 2) == b''
            writer.close()
            await writer.wait_closed()
    asyncio.run(run())


def test_no_ack_when_database_fails():
    class FailingStore:
        def authorize(self, imei):
            pass
        def save(self, imei, rows):
            raise RuntimeError('database unavailable')
    async def run():
        receiver = Receiver(FailingStore())
        server = await asyncio.start_server(receiver.handle, '127.0.0.1', 0)
        async with server:
            r, w = await asyncio.open_connection('127.0.0.1', server.sockets[0].getsockname()[1])
            w.write(ntcb(b'*>S:'+IMEI.encode(), 1, 0) + ntcb(negotiation(), 1, 0) + frame(record()))
            await w.drain()
            await read_frame(r, None)
            await read_frame(r, None)
            assert await asyncio.wait_for(r.read(), 2) == b''
            w.close()
            await w.wait_closed()
    asyncio.run(run())


def test_registration_owner_only_and_unique(tracker):
    client, vehicle, _ = tracker
    url = f'/api/v1/vehicles/{vehicle}/hardware-devices'
    body = {'name': 'START S-4011', 'imei': IMEI}
    assert client.post(url, json=body).status_code == 201
    assert client.post(url, json=body).status_code == 409
    assert client.post(url, json=dict(body, imei='invalid')).status_code == 422
    session = client.post('/api/v1/auth/login', json={'username': 'friend', 'password': 'viewer-password-123'}).json()
    client.headers['X-CSRF-Token'] = session['csrf_token']
    assert client.post(url, json=body).status_code == 403
